[package]
name = "slashing-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tokio = {version = "1", features = ["full"]}
rand = "0.9.2"
ed25519-dalek = "2.2.0"
tycho-types = { git = "https://github.com/broxus/tycho-types"}